---
- name: Add ACL Rule
  hosts: ckp
  connection: httpapi
  gather_facts: no

  tasks:


    - set_fact:
        # source_network: "{{ source_object | regex_search('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"
        source_network: "{{ source_object | regex_findall('(?<=\'\')(.*?)(?=\'\'\,)') }}"


    - debug:
        var: source_network
    # - name: Add Access Rule
    #   cp_mgmt_access_rule:
    #     layer: Network
    #     name: "{{ rule_name }}"
    #     source: "{{ source_object }}"
    #     destination: "{{ dest_object }}"
    #     action: "{{ rule_action }}"
    #     enabled: true
    #     position: top
    #     state: present
    #
    # - name: publish
    #   cp_mgmt_publish:
