#https://ash-sidhu.blog/2018/11/07/using-ansible-for-automating-tasks-on-checkpoint-firewall/
---
- name: Delete ACL Rule
  hosts: ckp
  connection: local
  gather_facts: no
  vars_files:
    - ./vars/default_vars.yml
    - ./credentials/gaia_credentials.yml

  tasks:

    - name: Create Web Services API Session
      uri:
        url: "https://{{ansible_host }}/web_api/login"
        method: POST
        headers:
          Content-Type: "application/json"
        body:
          user: "{{ GAIA_USERNAME }}"
          password: "{{ GAIA_PASSWORD }}"
        body_format: json
        return_content: yes
        validate_certs: False
      register: login_output

    # - debug:
    #     var: login_output

    - name: Discover existing sessions
      uri:
        url: "https://{{ansible_host }}/web_api/show-sessions"
        method: POST
        headers:
          Content-Type: "application/json"
          X-chkp-sid: "{{ login_output.json.sid }}"
        body:
          limit: 500
          offset: 0
        body_format: json
        return_content: yes
        validate_certs: False
      register: sessions_output

    # - debug:
    #     var: sessions_output

    - name: Delete existing sessions
      uri:
        url: "https://{{ansible_host }}/web_api/discard"
        method: POST
        headers:
          Content-Type: "application/json"
          X-chkp-sid: "{{ login_output.json.sid }}"
        body:
          uid: "{{ item.uid}}"
        body_format: json
        return_content: yes
        validate_certs: False
      loop: "{{ sessions_output.json.objects }}"

    - name: Retrieve Access Rulebase
      uri:
        url: "https://{{ansible_host }}/web_api/show-access-rulebase"
        method: POST
        headers:
          Content-Type: "application/json"
          X-chkp-sid: "{{ login_output.json.sid }}"
        body:
          limit: 50
          offset: 0
          name: Network
        body_format: json
        return_content: yes
        validate_certs: False
      register: rules_output

    - debug:
        var: rules_output.json

    - name: Delete Access Rule
      uri:
        url: "https://{{ansible_host }}/web_api/delete-access-rule"
        method: POST
        headers:
          Content-Type: "application/json"
          X-chkp-sid: "{{ login_output.json.sid }}"
        body:
          uid: "{{ item.uid }}"
          layer: Network
        body_format: json
        return_content: yes
        validate_certs: False
      loop: "{{ rules_output.json.rulebase }}"
      when: item.name == acl_to_delete

    - name: Publish changes
      uri:
        url: "https://{{ansible_host }}/web_api/v1.1/publish"
        method: POST
        headers:
          Content-Type: "application/json"
          X-chkp-sid: "{{ login_output.json.sid }}"
        body_format: raw
        body: "{ }"
        validate_certs: False

    - name: Terminate Web Services API Session
      uri:
        url: "https://{{ansible_host }}/web_api/logout"
        method: POST
        headers:
          Content-Type: "application/json"
          X-chkp-sid: "{{ login_output.json.sid }}"
        body_format: raw
        body: "{ }"
        validate_certs: False
