#https://ash-sidhu.blog/2018/11/07/using-ansible-for-automating-tasks-on-checkpoint-firewall/
---
- name: Delete Subnet Object
  hosts: ckp
  connection: httpapi
  gather_facts: no

  tasks:

    - name: Delete subnet object
      cp_mgmt_network:
        name: "{{ subnet_name }}"
        state: absent

    - name: publish
      cp_mgmt_publish:

    - name: List subnet objects
      cp_mgmt_network_facts:
      register: subnet_output

    # - name: debug subnets
    #   debug:
    #     var: subnet_output

    - copy:
        dest: /tmp/subnet_output.json
        content: "{{ subnet_output }}"
      run_once: yes
      delegate_to: localhost
