#https://ash-sidhu.blog/2018/11/07/using-ansible-for-automating-tasks-on-checkpoint-firewall/
---
- name: Update Ansible Tower Checkpoint Access Rule Job Template
  hosts: tower
  gather_facts: no
  vars_files:
    - ./credentials/tower-credentials.yml
    - /tmp/subnet_output.json

  tasks:
    - name: Build survey_spec from template
      template:
        src: ./templates/new-rule-survey.j2
        dest: /tmp/new-rule-survey.json

    - name: Update Ansible Tower Checkpoint Access Rule Job Template
      tower_job_template:
          name: "Checkpoint Add Access Rule"
          job_type: "run"
          inventory: "Cloud Checkpoint Firewalls"
          project: "Checkpoint Administration"
          playbook: "add-access-rule.yml"
          credential: "Checkpoint Firewall Machine Credential"
          survey_enabled: true
          survey_spec: "{{ lookup('file', '/tmp/new-rule-survey.json') }}"
          tower_username: "{{ TOWER_USERNAME }}"
          tower_password: "{{ TOWER_PASSWORD }}"
          tower_host: https://ansibletower.mford.io
          validate_certs: no
          diff_mode_enabled: yes
      delegate_to: localhost
      run_once: yes
